//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// FileOfficer.rc에서 사용되고 있습니다.
//
#define IDS_CONFIRM_EXIT                10
#define IDS_CONFIRM_TRASH               11
#define IDS_CONFIRM_DELETE              12
#define IDS_BKIMG_PATH                  13
#define IDS_COL_CLR_RULETYPE            14
#define IDS_COL_CLR_RULETEXT            15
#define IDS_COL_CLR_RULEBK              16
#define IDS_COL_CLR_RULEOPTION          17
#define IDS_NOCOLOR                     18
#define IDS_ITEM_COUNT                  19
#define IDS_TB_00                       20
#define IDS_TB_01                       21
#define IDS_TB_02                       22
#define IDS_TB_03                       23
#define IDS_TB_04                       24
#define IDS_TB_05                       25
#define IDS_TB_06                       26
#define IDS_TB_07                       27
#define IDS_TB_08                       28
#define IDS_TB_09                       29
#define IDS_TB_10                       30
#define IDS_TB_11                       31
#define IDS_TB_12                       32
#define IDS_LOADING_TIME                33
#define IDS_NOW_LOADING                 34
#define IDS_VIEW_CFG_EXPORT             35
#define IDS_VIEW_CFG_IMPORT             36
#define IDS_RENAME                      37
#define IDS_THIN                        38
#define IDS_ITALIC                      39
#define IDS_BOLD                        40
#define IDS_SELECTED_COUNT              41
#define IDS_INVALIDPATH                 42
#define IDS_PASTE_FILE                  43
#define IDS_CONVERT_NFD                 44
#define IDS_COL_MEMO                    45
#define IDS_MEMO_HIDDEN                 46
#define IDS_MEMO_READONLY               47
#define IDS_MEMO_COMPRESSED             48
#define IDS_MEMO_ENCRYPTED              49
#define IDS_MEMO_LOCKED                 50
#define IDS_CHECK_LOCKED                51
#define IDS_CONFIRM_CLOSE_SEARCH        52
#define IDS_MSG_FILERANGE_ERROR         53
#define IDS_MSG_TIMERANGE_ERROR         54
#define IDS_MSG_COLORRULE_DATEERR       55
#define IDS_MSG_COLORRULE_EERR          55
#define IDS_MSG_INVALIDFONTSIZE         56
#define IDS_ICON_LARGE                  57
#define IDS_ICON_SMALL                  58
#define IDS_ICON_EXLARGE                59
#define IDS_ICON_JUMBO                  60
#define IDS_COL_DRIVE_NAME              61
#define IDS_COL_DRIVE_PATH              62
#define IDS_COL_FREESPACE_DRIVE         63
#define IDS_COL_TOTALSPACE_DRIVE        64
#define IDS_COL_NAME_FOLDER             65
#define IDS_COL_DATE_FOLDER             66
#define IDS_COL_SIZE_FOLDER             67
#define IDS_COL_TYPE_FOLDER             68
#define IDS_COL_NAME_UNC                69
#define IDS_COL_EMPTY                   70
#define IDS_CLR_RULE_EXT                71
#define IDS_CLR_RULE_FOLDER             72
#define IDS_CLR_RULE_DATE               73
#define IDS_CLR_RULE_COLNAME            74
#define IDS_CLR_RULE_COLDATE            75
#define IDS_CLR_RULE_COLSIZE            76
#define IDS_CLR_RULE_COLTYPE            77
#define IDS_CLR_RULE_NAME               78
#define IDS_TB_SEARCH_00                79
#define IDS_TB_SEARCH_01                80
#define IDS_TB_SEARCH_02                81
#define IDS_TB_SEARCH_03                82
#define IDS_TB_SEARCH_04                83
#define IDS_TB_SEARCH_05                84
#define IDD_FILEOFFICER_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDR_TB_TAB                      133
#define IDD_TAB_VIEW                    135
#define IDD_CFG_VIEW                    138
#define IDB_TABICON                     142
#define IDD_INPUT                       143
#define IDD_CFG_LAYOUT                  145
#define IDR_MENU1                       147
#define IDD_COLOR_RULE                  148
#define IDS_CLR_RULE_EXT_GUIDE          151
#define IDS_CLR_RULE_DATE_GUIDE         152
#define IDS_CLR_RULE_NAME_GUIDE         153
#define IDR_MENU_SHORTCUT               155
#define IDR_MENU_TAB                    156
#define IDD_FILE_SEARCH                 158
#define IDR_TB_SEARCH                   162
#define IDC_TAB_PATH                    1001
#define IDC_EDIT_PATH                   1002
#define IDC_ST_BAR                      1003
#define IDC_ST_SHORTCUT                 1004
#define IDC_COLOR_TEXT                  1005
#define IDC_COLOR_BK                    1006
#define IDC_CHECK_DEFAULT_COLOR         1007
#define IDC_CHECK_DEFAULT_FONT          1008
#define IDC_EDIT_FONTSIZE               1009
#define IDC_CB_ICONSIZE                 1010
#define IDC_ST_COLOR_BK                 1011
#define IDC_EDIT_INPUT                  1011
#define IDC_ST_COLOR_TEXT               1012
#define IDC_ST_FONTSIZE                 1013
#define IDC_CHK_BOLD                    1014
#define IDC_ST_FONTNAME                 1014
#define IDC_RADIO_LAYOUT_HORIZONTAL     1015
#define IDC_ST_COLOR_RULE_TITLE         1015
#define IDC_RADIO_LAYOUT_VERTICAL       1016
#define IDC_EDIT_FONTNAME               1016
#define IDC_RADIO_LAYOUT_SINGLE_1       1017
#define IDC_RADIO_LAYOUT_SINGLE_2       1018
#define IDC_RADIO_LAYOUT_PERCENT        1019
#define IDC_RADIO_LAYOUT_FIXED_1        1020
#define IDC_RADIO_LAYOUT_FIXED          1020
#define IDC_RADIO_LAYOUT_FIXED_2        1021
#define IDC_RADIO_LAYOUT_DYNAMIC        1021
#define IDC_EDIT_LAYOUT_PERCENT         1022
#define IDC_EDIT_LAYOUT_FIXED_1         1023
#define IDC_EDIT_LAYOUT_FIXED_2         1024
#define IDC_CHECK_TOOLBARTEXT           1025
#define IDC_LIST_COLOR_RULE             1026
#define IDC_BTN_COLOR_RULE_ADD          1027
#define IDC_BTN_COLOR_RULE_EDIT         1028
#define IDC_BTN_COLOR_RULE_DEL          1029
#define IDC_BTN_COLOR_RULE_DOWN         1030
#define IDC_BTN_COLOR_RULE_UP           1031
#define IDC_EDIT_BKIMG_PATH             1032
#define IDC_BTN_BKIMG_PATH              1033
#define IDC_CHK_BKIMG                   1034
#define IDC_EDIT_FIND                   1035
#define IDC_BTN_VIEW_CFG_EXPORT         1035
#define IDC_BTN_FIND                    1036
#define IDC_BTN_VIEW_CFG_IMPORT         1036
#define IDC_CB_RULETYPE                 1037
#define IDC_BTN_FONT                    1037
#define IDC_EDIT_COLOR_RULE             1038
#define IDC_STATIC_INPUT_GUIDE          1039
#define IDC_STATIC_COLOR_RULE           1040
#define IDC_CHK_COLOR_TEXT              1041
#define IDC_CHK_COLOR_BK                1042
#define IDC_EDIT_LAYOUT_BTNSIZE         1042
#define IDC_CHECK_TOOLBAR_VERTICAL      1043
#define IDC_CHECK_VIEW_SHORTCUT_1       1044
#define IDC_CHECK_VIEW_SHORTCUT_2       1045
#define IDC_LIST_SHORTCUT               1046
#define IDC_CHECK_USEFILEICON           1047
#define IDC_ST_FILENAME                 1048
#define IDC_CHECK_USEFILETYPE           1049
#define IDC_ST_FILEEXT                  1050
#define IDC_ST_GUIDE                    1051
#define IDC_CHECK_CHECKOPEN             1052
#define IDC_ST_FILESIZE                 1053
#define IDC_ST_FILEDATETIME             1054
#define IDC_LIST_SEARCH                 1055
#define IDC_ST_FILESTATE                1056
#define IDC_EDIT_FILENAME               1057
#define IDC_EDIT_FILEEXT                1058
#define IDC_EDIT_FILESIZE_MIN           1059
#define IDC_EDIT_FILESIZE_MAX           1060
#define IDC_ST_FILEPATH                 1061
#define IDC_EDIT_FILEPATH               1062
#define IDC_FILE_TIME_FROM              1063
#define IDC_FILE_TIME_UNTIL             1064
#define IDC_FILE_DATE_FROM              1065
#define IDC_FILE_DATE_UNTIL             1066
#define IDC_CHK_DATETIME_FROM           1067
#define IDC_CHK_DATETIME_UNTIL          1068
#define IDC_CHK_FILESTATE_LOCKED        1069
#define IDC_CHK_FILESTATE_HIDDEN        1070
#define IDC_CHK_FILESTATE_READONLY      1071
#define IDC_CHK_FILESTATE_ENCRYPTED     1072
#define IDC_ST_SIZERANGE                1073
#define IDC_ST_DATETIMERANGE            1074
#define IDC_BTN_SEARCH_START            1075
#define IDC_CB_NAME                     1076
#define IDC_ST_FILEEXT2                 1077
#define IDC_EDIT1                       1077
#define IDC_EDIT_SEARCH_MSG             1078
#define IDM_PLAY_ITEM                   32772
#define IDM_OPEN_PARENT                 32773
#define IDM_ADD_LIST                    32774
#define IDM_CLOSE_LIST                  32775
#define IDM_CONFIG                      32776
#define IDM_REFRESH_LIST                32779
#define IDM_TOGGLE_VIEW                 32780
#define IDM_CFG_LAYOUT                  32780
#define IDM_OPEN_PREV                   32784
#define IDM_OPEN_NEXT                   32785
#define IDM_PASTE_FILE                  32789
#define IDM_TOGGLE_FIND                 32790
#define IDM_FILE_PASTE                  32791
#define IDM_FILE_CUT                    32792
#define IDM_FILE_DELETE                 32793
#define IDM_FILE_COPY                   32795
#define IDM_CONVERT_NFD                 32796
#define IDM_SHORTCUT_OPEN               32801
#define IDM_SHORTCUT_OPTION             32802
#define IDM_SHORTCUT_REMOVE             32803
#define IDM_SHORTCUT_VIEWFOLDER         32804
#define IDM_SHORTCUT_COPY               32805
#define IDM_SHORTCUT_REMOVEFROMLIST     32806
#define IDM_SHORTCUT_CUT                32807
#define IDM_SHORTCUT_DELETE             32808
#define IDM_SHORTCUT_REFRESH            32812
#define IDM_SHORTCUT_UP                 32813
#define ID_POPUP_32814                  32814
#define IDM_SHORTCUT_DOWN               32815
#define IDM_TAB_LEFT                    32816
#define ID_POPUP_32817                  32817
#define IDM_TAB_RIGHT                   32818
#define IDM_TAB_CLOSE                   32819
#define IDM_TAB_ADD                     32820
#define ID_32821                        32821
#define ID_32822                        32822
#define IDM_SHORTCUT_LARGEICON          32823
#define IDM_SHORTCUT_SMALLICON          32824
#define ID_POPUP_32825                  32825
#define IDM_SHORTCUT_ICONVIEW           32826
#define ID_32827                        32827
#define IDM_SHORTCUT_LISTVIEW           32828
#define IDM_SHORTCUT_REPORTVIEW         32829
#define ID_32830                        32830
#define IDM_SHORTCUT_LARGEGICON         32831
#define IDM_SHORTCUT_ICON               32832
#define IDM_SHORTCUT_JUMBO              32833
#define IDM_SHORTCUT_ICONSIZE_32        32834
#define IDM_SHORTCUT_ICONSIZE_16        32835
#define IDM_SHORTCUT_ICONSIZE_48        32836
#define IDM_SHORTCUT_ICONSIZE_256       32837
#define IDM_CHECK_LOCKED                32838
#define IDM_TOGGLE_SEARCHDLG            32841
#define IDM_SEARCH_BEGIN                32842
#define IDM_SEARCH_STOP                 32843
#define IDM_SEARCH_CLEAR                32844
#define IDM_SEARCH_SETTING              32845
#define IDM_SEARCH_CRITERIA_LOAD        32847
#define IDM_SEARCH_CRITERIA_SAVE        32848
#define IDM_CRITERIA_LOAD               32850

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32851
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
