//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// FileOfficer.rc에서 사용되고 있습니다.
//
#define IDS_CONFIRM_EXIT                10
#define IDS_CONFIRM_TRASH               11
#define IDS_CONFIRM_DELETE              12
#define IDS_BKIMG_PATH                  13
#define IDS_COL_CLR_RULETYPE            14
#define IDS_COL_CLR_RULETEXT            15
#define IDS_COL_CLR_RULEBK              16
#define IDS_COL_CLR_RULEOPTION          17
#define IDS_NOCOLOR                     18
#define IDS_ITEM_COUNT                  19
#define IDS_TB_00                       20
#define IDS_TB_01                       21
#define IDS_TB_02                       22
#define IDS_TB_03                       23
#define IDS_TB_04                       24
#define IDS_TB_05                       25
#define IDS_TB_06                       26
#define IDS_TB_07                       27
#define IDS_TB_08                       28
#define IDS_TB_09                       29
#define IDS_TB_10                       30
#define IDS_TB_11                       31
#define IDS_TB_12                       32
#define IDS_LOADING_TIME                33
#define IDS_NOW_LOADING                 34
#define IDS_VIEW_CFG_EXPORT             35
#define IDS_VIEW_CFG_IMPORT             36
#define IDS_RENAME                      37
#define IDS_THIN                        38
#define IDS_ITALIC                      39
#define IDS_BOLD                        40
#define IDS_SELECTED_COUNT              41
#define IDS_MSG_COLORRULE_DATEERR       55
#define IDS_MSG_COLORRULE_EERR          55
#define IDS_MSG_INVALIDFONTSIZE         56
#define IDS_ICON_LARGE                  57
#define IDS_ICON_SMALL                  58
#define IDS_ICON_EXLARGE                59
#define IDS_ICON_JUMBO                  60
#define IDS_COL_NAME_DRIVE              61
#define IDS_COL_ALIAS_DRIVE             62
#define IDS_COL_FREESPACE_DRIVE         63
#define IDS_COL_TOTALSPACE_DRIVE        64
#define IDS_COL_NAME_FOLDER             65
#define IDS_COL_DATE_FOLDER             66
#define IDS_COL_SIZE_FOLDER             67
#define IDS_COL_TYPE_FOLDER             68
#define IDS_COL_NAME_UNC                69
#define IDS_COL_EMPTY                   70
#define IDS_CLR_RULE_EXT                71
#define IDS_CLR_RULE_FOLDER             72
#define IDS_CLR_RULE_DATE               73
#define IDS_CLR_RULE_COLNAME            74
#define IDS_CLR_RULE_COLDATE            75
#define IDS_CLR_RULE_COLSIZE            76
#define IDS_CLR_RULE_COLTYPE            77
#define IDS_CLR_RULE_NAME               78
#define IDD_FILEOFFICER_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDR_TB_TAB                      133
#define IDD_TAB_VIEW                    135
#define IDD_CFG_VIEW                    138
#define IDB_TABICON                     142
#define IDD_INPUT                       143
#define IDD_CFG_LAYOUT                  145
#define IDR_MENU1                       147
#define IDD_COLOR_RULE                  148
#define IDS_CLR_RULE_EXT_GUIDE          151
#define IDS_CLR_RULE_DATE_GUIDE         152
#define IDS_CLR_RULE_NAME_GUIDE         153
#define IDC_TAB_PATH                    1001
#define IDC_EDIT_PATH                   1002
#define IDC_ST_BAR                      1003
#define IDC_COLOR_TEXT                  1005
#define IDC_COLOR_BK                    1006
#define IDC_CHECK_DEFAULT_COLOR         1007
#define IDC_CHECK_DEFAULT_FONT          1008
#define IDC_EDIT_FONTSIZE               1009
#define IDC_CB_ICONSIZE                 1010
#define IDC_ST_COLOR_BK                 1011
#define IDC_EDIT_INPUT                  1011
#define IDC_ST_COLOR_TEXT               1012
#define IDC_ST_FONTSIZE                 1013
#define IDC_CHK_BOLD                    1014
#define IDC_ST_FONTNAME                 1014
#define IDC_RADIO_LAYOUT_HORIZONTAL     1015
#define IDC_ST_COLOR_RULE_TITLE         1015
#define IDC_RADIO_LAYOUT_VERTICAL       1016
#define IDC_EDIT_FONTNAME               1016
#define IDC_RADIO_LAYOUT_SINGLE_1       1017
#define IDC_RADIO_LAYOUT_SINGLE_2       1018
#define IDC_RADIO_LAYOUT_PERCENT        1019
#define IDC_RADIO_LAYOUT_FIXED_1        1020
#define IDC_RADIO_LAYOUT_FIXED_2        1021
#define IDC_EDIT_LAYOUT_PERCENT         1022
#define IDC_EDIT_LAYOUT_FIXED_1         1023
#define IDC_EDIT_LAYOUT_FIXED_2         1024
#define IDC_CHECK_TOOLBARTEXT           1025
#define IDC_LIST_COLOR_RULE             1026
#define IDC_BTN_COLOR_RULE_ADD          1027
#define IDC_BTN_COLOR_RULE_EDIT         1028
#define IDC_BTN_COLOR_RULE_DEL          1029
#define IDC_BTN_COLOR_RULE_DOWN         1030
#define IDC_BTN_COLOR_RULE_UP           1031
#define IDC_EDIT_BKIMG_PATH             1032
#define IDC_BTN_BKIMG_PATH              1033
#define IDC_CHK_BKIMG                   1034
#define IDC_EDIT_FIND                   1035
#define IDC_BTN_VIEW_CFG_EXPORT         1035
#define IDC_BTN_FIND                    1036
#define IDC_BTN_VIEW_CFG_IMPORT         1036
#define IDC_CB_RULETYPE                 1037
#define IDC_BTN_FONT                    1037
#define IDC_EDIT_COLOR_RULE             1038
#define IDC_STATIC_INPUT_GUIDE          1039
#define IDC_STATIC_COLOR_RULE           1040
#define IDC_CHK_COLOR_TEXT              1041
#define IDC_CHK_COLOR_BK                1042
#define IDM_PLAY_ITEM                   32772
#define IDM_OPEN_PARENT                 32773
#define IDM_ADD_LIST                    32774
#define IDM_CLOSE_LIST                  32775
#define IDM_CONFIG                      32776
#define IDM_SET_PATH_1                  32777
#define IDM_SET_PATH                    32777
#define IDM_REFRESH_LIST                32779
#define IDM_TOGGLE_VIEW                 32780
#define IDM_CFG_LAYOUT                  32780
#define IDM_OPEN_PREV                   32784
#define IDM_OPEN_NEXT                   32785
#define ID_POPUP_32788                  32788
#define IDM_PASTE_FILE                  32789
#define IDM_TOGGLE_FIND                 32790
#define IDM_FILE_PASTE                  32791
#define IDM_FILE_CUT                    32792
#define IDM_FILE_DELETE                 32793
#define IDM_FILE_COPY                   32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
